"""add operating condition telemetry

Revision ID: 2f3f37c3fb4c
Revises: 1f2e5c845254
Create Date: 2026-09-26 11:26:14.734581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3f37c3fb4c'
down_revision: Union[str, Sequence[str], None] = '1f2e5c845254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column(
        "telemetry",
        sa.Column(
            "throttle",
            sa.Float(),
            nullable=False,
            server_default=sa.text("1.0"),
        ),
    )

    op.add_column(
        "telemetry",
        sa.Column(
            "engine_load",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.5"),
        ),
    )

    op.add_column(
        "telemetry",
        sa.Column(
            "altitude",
            sa.Float(),
            nullable=False,
            server_default=sa.text("0.0"),
        ),
    )

    op.add_column(
        "telemetry",
        sa.Column(
            "ambient_temperature",
            sa.Float(),
            nullable=False,
            server_default=sa.text("25.0"),
        ),
    )

    op.alter_column(
        "telemetry",
        "throttle",
        server_default=None,
    )

    op.alter_column(
        "telemetry",
        "engine_load",
        server_default=None,
    )

    op.alter_column(
        "telemetry",
        "altitude",
        server_default=None,
    )

    op.alter_column(
        "telemetry",
        "ambient_temperature",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetry', 'ambient_temperature')
    op.drop_column('telemetry', 'altitude')
    op.drop_column('telemetry', 'engine_load')
    op.drop_column('telemetry', 'throttle')
    # ### end Alembic commands ###
