"""add health snapshots

Revision ID: 4f1b64de01fa
Revises: 21872b55c26f
Create Date: 2026-09-01 18:28:10.238262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1b64de01fa'
down_revision: Union[str, Sequence[str], None] = '21872b55c26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine_id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('thermal', sa.Float(), nullable=False),
    sa.Column('combustion', sa.Float(), nullable=False),
    sa.Column('lubrication', sa.Float(), nullable=False),
    sa.Column('mechanical', sa.Float(), nullable=False),
    sa.Column('electrical', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_snapshots')
    # ### end Alembic commands ###
