"""add ingestion events

Revision ID: 826ff0d83aae
Revises: 13f677398608
Create Date: 2026-08-29 21:35:04.655368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826ff0d83aae'
down_revision: Union[str, Sequence[str], None] = '13f677398608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('telemetry_time_idx'), 'telemetry', [sa.literal_column('time DESC')], unique=False)
    op.drop_table('ingestion_events')
    # ### end Alembic commands ###
