% -------------------------------------------------------------------
%  Generated by MATLAB on 3-Sep-2026 00:10:56
%  MATLAB version: 26.1.0.3346908 (R2026a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('some_generated_data.mat');

BSFC_nominal = 280;

CHT_capacity = 500;

CHT_init = 25;

C_oil = 5000;

EGT_tau = 0.8;

Fault_ID = 0;

J_engine = 0.05;

L_lapse = 0.0065;

OilTemp_init = 25;

Oil_capacity = 250;

P0 = 101325;

RPM_idle = 1500;

RPM_max = 7500;

R_air = 287.05;

T0 = 288.15;

T_max = 10;

T_oil_ref = 90;

Ts_telemetry_fast = 0.005;

Ts_telemetry_slow = 0.5;

Ts_telemetry_std = 0.1;

all_data = [];

ans = 0;

drift_cht = 0.001;

drift_egt = 0.002;

drift_oilp = -0.0005;

f_id = 0;

friction_a = 0.001;

friction_b = 5E-5;

fuel_min = 0.2;

g_gravity = 9.80665;

i = 15;

k1_egt = 150;

k2_egt = 100;

k3_egt = 0.05;

k_c = 0.5;

k_h = 5000;

k_oil_cool = 0.05;

k_oil_heat = 2.5;

k_vib_amp = 0.001;

kp_oil = 0.015;

kt_oil = 0.2;

model = 'AeroPistonEngineSimulator';

model_name = 'AeroPistonEngineTwin';

noise_cht = 0.05;

noise_egt = 0.2;

noise_fuel = 0.001;

noise_oilp = 0.05;

noise_oilt = 0.02;

noise_rpm = 0.01;

noise_vib = 0.1;

out = saveVarsMat.out; % <1x1 Simulink.SimulationOutput> unsupported class

rho0 = 1.225;

run = 1;

signals = saveVarsMat.signals; % <1x1 struct> unsupported class at signals.signal1

t = saveVarsMat.t; % <12001x1 double> too many elements

tau_cht_sensor = 3;

tau_egt_sensor = 0.8;

tau_fuel_sensor = 0.2;

tau_oilp_sensor = 0.1;

tau_oilt_sensor = 2;

tau_rpm_sensor = 0.05;

tau_vib_sensor = 0.005;

u = saveVarsMat.u; % <12001x4 double> too many elements

vib_noise_pwr = 0.1;

clear saveVarsMat;
